-- MySQL Script generated by MySQL Workbench
-- Mon May  9 19:43:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema redlight
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `redlight`;

-- -----------------------------------------------------
-- Schema redlight
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `redlight` DEFAULT CHARACTER SET utf8;
USE `redlight`;

-- -----------------------------------------------------
-- Table `rl_house`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rl_house`;

CREATE TABLE IF NOT EXISTS `rl_house`
(
    `house_id`    INT          NOT NULL AUTO_INCREMENT COMMENT '房屋主键',
    `is_sold`     TINYINT      NOT NULL DEFAULT 0 COMMENT '是否卖出，\'1\'已卖出，’0‘未卖出',
    `click`       INT          NOT NULL DEFAULT 0 COMMENT '点击次数',
    `name`        VARCHAR(45)  NOT NULL COMMENT '房屋名称',
    `address`     VARCHAR(45)  NOT NULL COMMENT '地址',
    `size`        INT          NULL COMMENT '面积',
    `division`    VARCHAR(45)  NULL COMMENT '区域',
    `price`       INT          NULL COMMENT '单位价格',
    `type`        VARCHAR(45)  NULL COMMENT '房屋类型',
    `description` VARCHAR(200) NULL COMMENT '房屋描述',
    `picture`     VARCHAR(200) NULL COMMENT '图片链接',
    PRIMARY KEY (`house_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rl_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rl_client`;

CREATE TABLE IF NOT EXISTS `rl_client`
(
    `client_id` INT         NOT NULL AUTO_INCREMENT COMMENT '客户主键',
    `nick_name` VARCHAR(45) NOT NULL COMMENT '用户昵称',
    `username`  VARCHAR(45) NULL COMMENT '用户名',
    `password`  VARCHAR(45) NOT NULL COMMENT '密码',
    `location`  VARCHAR(45) NULL COMMENT '地址',
    `email`     VARCHAR(45) NULL COMMENT '邮箱',
    `phone`     VARCHAR(45) NULL COMMENT '电话',
    PRIMARY KEY (`client_id`),
    UNIQUE INDEX `nick_name_UNIQUE` (`nick_name` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rl_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rl_admin`;

CREATE TABLE IF NOT EXISTS `rl_admin`
(
    `admin_id`  INT         NOT NULL AUTO_INCREMENT,
    `nick_name` VARCHAR(45) NOT NULL,
    `username`  VARCHAR(45) NULL,
    `password`  VARCHAR(45) NOT NULL,
    `location`  VARCHAR(45) NULL,
    `email`     VARCHAR(45) NULL,
    `phone`     VARCHAR(45) NULL,
    PRIMARY KEY (`admin_id`),
    UNIQUE INDEX `nick_name_UNIQUE` (`nick_name` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rl_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rl_comment`;

CREATE TABLE IF NOT EXISTS `rl_comment`
(
    `comment_id`  INT          NOT NULL AUTO_INCREMENT COMMENT '评论主键',
    `creator_id`  INT          NOT NULL COMMENT '评论创建者，外键',
    `create_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论创建时间',
    `info`        VARCHAR(200) NOT NULL COMMENT '评论信息',
    `is_replied`  TINYINT      NOT NULL DEFAULT 0 COMMENT '是否已回复',
    `reply_id`    INT          NULL COMMENT '评论回复者，外键',
    `reply_time`  DATETIME     NULL COMMENT '评论时间',
    `reply_info`  VARCHAR(200) NULL COMMENT '回复信息',
    PRIMARY KEY (`comment_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rl_view_appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rl_view_appointment`;

CREATE TABLE IF NOT EXISTS `rl_view_appointment`
(
    `view_appointment_id` INT      NOT NULL AUTO_INCREMENT COMMENT '看房预约主键',
    `house_id`            INT      NOT NULL COMMENT '房屋主键，外键',
    `creator_id`          INT      NOT NULL COMMENT '创建者主键，外键',
    `create_time`         DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `view_time`           DATETIME NOT NULL COMMENT '预约看房时间',
    `is_replied`          TINYINT  NULL DEFAULT 0 COMMENT '是否已回复',
    `replyer_id`          INT      NULL COMMENT '回复者主键，外键',
    `reply_time`          DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '回复时间',
    `is_viewed`           TINYINT  NULL DEFAULT 0 COMMENT '是否完成看房',
    PRIMARY KEY (`view_appointment_id`)
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
